// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneSwiss.Server;

#nullable disable

namespace OneSwiss.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825191358_AddErrorReportsHashIndex")]
    partial class AddErrorReportsHashIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessGroupApplicationRole", b =>
                {
                    b.Property<Guid>("AccessGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("AccessGroupsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("AccessGroupApplicationRole");
                });

            modelBuilder.Entity("AccessGroupUsersGroup", b =>
                {
                    b.Property<Guid>("AccessGroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersGroupsId")
                        .HasColumnType("uuid");

                    b.HasKey("AccessGroupsId", "UsersGroupsId");

                    b.HasIndex("UsersGroupsId");

                    b.ToTable("AccessGroupUsersGroup");
                });

            modelBuilder.Entity("AgentMaintenanceTask", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintenanceTasksId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentsId", "MaintenanceTasksId");

                    b.HasIndex("MaintenanceTasksId");

                    b.ToTable("AgentMaintenanceTask");
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.Property<Guid>("AgentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechLogSeancesId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentsId", "TechLogSeancesId");

                    b.HasIndex("TechLogSeancesId");

                    b.ToTable("AgentTechLogSeance");
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.Property<Guid>("InfoBasesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintenanceTasksId")
                        .HasColumnType("uuid");

                    b.HasKey("InfoBasesId", "MaintenanceTasksId");

                    b.HasIndex("MaintenanceTasksId");

                    b.ToTable("InfoBaseMaintenanceTask");
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.Property<Guid>("SeancesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplatesId")
                        .HasColumnType("uuid");

                    b.HasKey("SeancesId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("LogTemplateTechLogSeance");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.AccessGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccessGroups");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.AgentClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AgentClients");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExternalName")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterInternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("RagentPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid");

                    b.Property<int>("LastReadVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("ConfigRepositories");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryMiddlewareArgument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrServerProxyMiddlewareId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CrServerProxyMiddlewareId");

                    b.ToTable("ConfigurationRepositoryMiddlewareArgument");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("GitUser")
                        .HasColumnType("text");

                    b.Property<Guid>("InternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ConfigRepositoryUsers");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CrServerProxyMiddlewareId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationRepositoryId");

                    b.HasIndex("CrServerProxyMiddlewareId");

                    b.ToTable("CrServerProxyLocations");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxyMiddleware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ConnectAll")
                        .HasColumnType("boolean");

                    b.Property<bool>("DebugMode")
                        .HasColumnType("boolean");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("CrServerProxyMiddlewares");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CrServerProxySettings");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Credentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DefaultConfigRepositoriesAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("DefaultForClusters")
                        .HasColumnType("boolean");

                    b.Property<bool>("DefaultV8Admin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsToken")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CustomNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("NotificationRecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRecipientId");

                    b.ToTable("CustomNotifications");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Dbms", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dbms");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ErrorLoggingServiceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportsTtl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ErrorLoggingServiceSettings");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ErrorReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Screenshot")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("ErrorReports");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogExportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InfoBaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Ttl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InfoBaseId");

                    b.ToTable("EventLogExportItems");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DbmsId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultTtl")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("InfoBaseNameRegex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("EventLogSettings");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.ToTable("GitRepositories");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.InfoBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uuid");

                    b.Property<string>("InfoBaseInternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfoBaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublishAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("InfoBases");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.LogTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogTemplates");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LeftStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintenanceTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("NodeKind")
                        .HasColumnType("integer");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("PreviousStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RightStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("MaintenanceSteps");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CommonDestination")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FinishDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFaulted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StartWhenDiscoverNewConfigVersion")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTasks");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTaskLogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InfoBaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InfoBaseId");

                    b.HasIndex("StepId");

                    b.HasIndex("TaskId");

                    b.ToTable("MaintenanceTaskLogs");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Additionalinfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("CustomNotificationsKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("NotificationTypes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("SendTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TechLogFilters");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSeance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DirectSending")
                        .HasColumnType("boolean");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TechLogSeances");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CredentialsId")
                        .HasColumnType("uuid");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DbmsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("TechLogSettings");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TelegramBotSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TelegramBotSettings");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("UsersGroups");
                });

            modelBuilder.Entity("AccessGroupApplicationRole", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("AccessGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessGroupUsersGroup", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("AccessGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.UsersGroup", null)
                        .WithMany()
                        .HasForeignKey("UsersGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentMaintenanceTask", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("TechLogSeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.InfoBase", null)
                        .WithMany()
                        .HasForeignKey("InfoBasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("SeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.LogTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.UsersGroup", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", "Agent")
                        .WithMany("Clusters")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("Clusters")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("ConfigurationRepositories")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryMiddlewareArgument", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.CrServerProxyMiddleware", null)
                        .WithMany("Arguments")
                        .HasForeignKey("CrServerProxyMiddlewareId");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryUser", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "Repository")
                        .WithMany("Users")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxyLocation", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "ConfigurationRepository")
                        .WithMany()
                        .HasForeignKey("ConfigurationRepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.CrServerProxyMiddleware", null)
                        .WithMany("Locations")
                        .HasForeignKey("CrServerProxyMiddlewareId");

                    b.Navigation("ConfigurationRepository");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxyMiddleware", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.Navigation("File");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CustomNotification", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.NotificationRecipient", null)
                        .WithMany("CustomNotifications")
                        .HasForeignKey("NotificationRecipientId");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogExportItem", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.InfoBase", "InfoBase")
                        .WithMany()
                        .HasForeignKey("InfoBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoBase");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogSettings", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OneSwiss.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.GitRepository", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Credentials", "Token")
                        .WithMany("GitRepositories")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.InfoBase", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Cluster", "Cluster")
                        .WithMany("InfoBases")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("InfoBases")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Steps")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.CopyInfoBaseStep", "CopyInfoBaseStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DestinationCredentialsId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("DestinationInfoBaseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SourceCredentialsId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SourceInfoBaseId")
                                .HasColumnType("uuid");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("DestinationCredentialsId");

                            b1.HasIndex("DestinationInfoBaseId");

                            b1.HasIndex("SourceCredentialsId");

                            b1.HasIndex("SourceInfoBaseId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.Credentials", "DestinationCredentials")
                                .WithMany()
                                .HasForeignKey("DestinationCredentialsId");

                            b1.HasOne("OneSwiss.Server.Models.InfoBase", "DestinationInfoBase")
                                .WithMany()
                                .HasForeignKey("DestinationInfoBaseId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.HasOne("OneSwiss.Server.Models.Credentials", "SourceCredentials")
                                .WithMany()
                                .HasForeignKey("SourceCredentialsId");

                            b1.HasOne("OneSwiss.Server.Models.InfoBase", "SourceInfoBase")
                                .WithMany()
                                .HasForeignKey("SourceInfoBaseId");

                            b1.Navigation("DestinationCredentials");

                            b1.Navigation("DestinationInfoBase");

                            b1.Navigation("SourceCredentials");

                            b1.Navigation("SourceInfoBase");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.DeleteExtensionStep", "DeleteExtensionStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExtensionName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("MaintenanceStepId");

                            b1.ToTable("MaintenanceSteps");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.ExecuteOneScriptStep", "ExecuteOneScriptStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("DebugMode")
                                .HasColumnType("boolean");

                            b1.Property<string>("ExecutablePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LoadConfigurationStep", "LoadConfigurationStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ConfigurationRepositoryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("FromConfigRepository")
                                .HasColumnType("boolean");

                            b1.Property<bool>("LoadExactVersion")
                                .HasColumnType("boolean");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("ConfigurationRepositoryId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "ConfigurationRepository")
                                .WithMany()
                                .HasForeignKey("ConfigurationRepositoryId");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("ConfigurationRepository");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LoadExtensionStep", "LoadExtensionStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("BaseConfigurationRepositoryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ConfigurationRepositoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExtensionName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("FromConfigRepository")
                                .HasColumnType("boolean");

                            b1.Property<bool>("LoadExactVersion")
                                .HasColumnType("boolean");

                            b1.Property<int>("Version")
                                .HasColumnType("integer");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("BaseConfigurationRepositoryId");

                            b1.HasIndex("ConfigurationRepositoryId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "BaseConfigurationRepository")
                                .WithMany()
                                .HasForeignKey("BaseConfigurationRepositoryId");

                            b1.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "ConfigurationRepository")
                                .WithMany()
                                .HasForeignKey("ConfigurationRepositoryId");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("BaseConfigurationRepository");

                            b1.Navigation("ConfigurationRepository");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LockConnectionsStep", "LockConnectionsStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccessCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.HasKey("MaintenanceStepId");

                            b1.ToTable("MaintenanceSteps");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.StartExternalDataProcessorStep", "StartExternalDataProcessorStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.UpdateConfigurationStep", "UpdateConfigurationStep", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceStepId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.Navigation("CopyInfoBaseStep");

                    b.Navigation("DeleteExtensionStep");

                    b.Navigation("ExecuteOneScriptStep");

                    b.Navigation("LoadConfigurationStep");

                    b.Navigation("LoadExtensionStep");

                    b.Navigation("LockConnectionsStep");

                    b.Navigation("MaintenanceTask");

                    b.Navigation("StartExternalDataProcessorStep");

                    b.Navigation("UpdateConfigurationStep");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTaskLogItem", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.InfoBase", "InfoBase")
                        .WithMany()
                        .HasForeignKey("InfoBaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", "Step")
                        .WithMany("Logs")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InfoBase");

                    b.Navigation("Step");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSettings", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OneSwiss.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.UsersGroup", "Parent")
                        .WithMany("Groups")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Agent", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CrServerProxyMiddleware", b =>
                {
                    b.Navigation("Arguments");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Credentials", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("ConfigurationRepositories");

                    b.Navigation("GitRepositories");

                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.NotificationRecipient", b =>
                {
                    b.Navigation("CustomNotifications");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
