// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneSwiss.Server;

#nullable disable

namespace OneSwiss.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("AccessGroupApplicationRole", b =>
                {
                    b.Property<string>("AccessGroupsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesId")
                        .HasColumnType("TEXT");

                    b.HasKey("AccessGroupsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("AccessGroupApplicationRole", (string)null);
                });

            modelBuilder.Entity("AccessGroupUsersGroup", b =>
                {
                    b.Property<string>("AccessGroupsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsersGroupsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AccessGroupsId", "UsersGroupsId");

                    b.HasIndex("UsersGroupsId");

                    b.ToTable("AccessGroupUsersGroup", (string)null);
                });

            modelBuilder.Entity("AgentMaintenanceTask", b =>
                {
                    b.Property<string>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceTasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "MaintenanceTasksId");

                    b.HasIndex("MaintenanceTasksId");

                    b.ToTable("AgentMaintenanceTask", (string)null);
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.Property<string>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechLogSeancesId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "TechLogSeancesId");

                    b.HasIndex("TechLogSeancesId");

                    b.ToTable("AgentTechLogSeance", (string)null);
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.Property<string>("InfoBasesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceTasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("InfoBasesId", "MaintenanceTasksId");

                    b.HasIndex("MaintenanceTasksId");

                    b.ToTable("InfoBaseMaintenanceTask", (string)null);
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.Property<string>("SeancesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplatesId")
                        .HasColumnType("TEXT");

                    b.HasKey("SeancesId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("LogTemplateTechLogSeance", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.AccessGroup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessGroups", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RagentPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Clusters", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("ConfigRepositories", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ConfigRepositoryUsers", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Credentials", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultConfigRepositoriesAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultForClusters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultV8Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CustomNotification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationRecipientId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRecipientId");

                    b.ToTable("CustomNotifications", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Dbms", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dbms", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ErrorLoggingServiceSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportsTtl")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ErrorLoggingServiceSettings", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ErrorReport", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Screenshot")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ErrorReports", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoBaseNameRegex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("EventLogSettings", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.File", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.InfoBase", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("InfoBases", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.LogTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogTemplates", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftStepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeKind")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("PreviousStepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightStepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("MaintenanceSteps", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CommonDestination")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("FinishDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFaulted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTasks", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTaskLogItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoBaseId");

                    b.HasIndex("StepId");

                    b.HasIndex("TaskId");

                    b.ToTable("MaintenanceTaskLogs", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Additionalinfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("CustomNotificationsKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.NotificationRecipient", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("NotificationTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SendTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationRecipients", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogFilter", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TechLogFilters", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSeance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirectSending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TechLogSeances", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("TechLogSettings", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TelegramBotSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TelegramBotSettings", (string)null);
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("UsersGroups", (string)null);
                });

            modelBuilder.Entity("AccessGroupApplicationRole", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("AccessGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessGroupUsersGroup", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.AccessGroup", null)
                        .WithMany()
                        .HasForeignKey("AccessGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.UsersGroup", null)
                        .WithMany()
                        .HasForeignKey("UsersGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentMaintenanceTask", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("TechLogSeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.InfoBase", null)
                        .WithMany()
                        .HasForeignKey("InfoBasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("SeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.LogTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.UsersGroup", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", "Agent")
                        .WithMany("Clusters")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("Clusters")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("ConfigurationRepositories")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepositoryUser", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "Repository")
                        .WithMany("Users")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.CustomNotification", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.NotificationRecipient", null)
                        .WithMany("CustomNotifications")
                        .HasForeignKey("NotificationRecipientId");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.EventLogSettings", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OneSwiss.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.InfoBase", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Cluster", "Cluster")
                        .WithMany("InfoBases")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany("InfoBases")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cluster");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Steps")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.CopyInfoBaseStep", "CopyInfoBaseStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DestinationCredentialsId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DestinationInfoBaseId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceCredentialsId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SourceInfoBaseId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("DestinationCredentialsId");

                            b1.HasIndex("DestinationInfoBaseId");

                            b1.HasIndex("SourceCredentialsId");

                            b1.HasIndex("SourceInfoBaseId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.Credentials", "DestinationCredentials")
                                .WithMany()
                                .HasForeignKey("DestinationCredentialsId");

                            b1.HasOne("OneSwiss.Server.Models.InfoBase", "DestinationInfoBase")
                                .WithMany()
                                .HasForeignKey("DestinationInfoBaseId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.HasOne("OneSwiss.Server.Models.Credentials", "SourceCredentials")
                                .WithMany()
                                .HasForeignKey("SourceCredentialsId");

                            b1.HasOne("OneSwiss.Server.Models.InfoBase", "SourceInfoBase")
                                .WithMany()
                                .HasForeignKey("SourceInfoBaseId");

                            b1.Navigation("DestinationCredentials");

                            b1.Navigation("DestinationInfoBase");

                            b1.Navigation("SourceCredentials");

                            b1.Navigation("SourceInfoBase");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.DeleteExtensionStep", "DeleteExtensionStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExtensionName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.ExecuteOneScriptStep", "ExecuteOneScriptStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("DebugMode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ExecutablePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LoadConfigurationStep", "LoadConfigurationStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ConfigurationRepositoryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("FromConfigRepository")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("ConfigurationRepositoryId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "ConfigurationRepository")
                                .WithMany()
                                .HasForeignKey("ConfigurationRepositoryId");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("ConfigurationRepository");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LoadExtensionStep", "LoadExtensionStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ConfigurationRepositoryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExtensionName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("FromConfigRepository")
                                .HasColumnType("INTEGER");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("ConfigurationRepositoryId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.ConfigurationRepository", "ConfigurationRepository")
                                .WithMany()
                                .HasForeignKey("ConfigurationRepositoryId");

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("ConfigurationRepository");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.LockConnectionsStep", "LockConnectionsStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AccessCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.StartExternalDataProcessorStep", "StartExternalDataProcessorStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.OwnsOne("OneSwiss.Server.Models.MaintenanceTasks.UpdateConfigurationStep", "UpdateConfigurationStep", b1 =>
                        {
                            b1.Property<string>("MaintenanceStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FileId")
                                .HasColumnType("TEXT");

                            b1.HasKey("MaintenanceStepId");

                            b1.HasIndex("FileId");

                            b1.ToTable("MaintenanceSteps", (string)null);

                            b1.HasOne("OneSwiss.Server.Models.File", "File")
                                .WithMany()
                                .HasForeignKey("FileId");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceStepId");

                            b1.Navigation("File");
                        });

                    b.Navigation("CopyInfoBaseStep");

                    b.Navigation("DeleteExtensionStep");

                    b.Navigation("ExecuteOneScriptStep");

                    b.Navigation("LoadConfigurationStep");

                    b.Navigation("LoadExtensionStep");

                    b.Navigation("LockConnectionsStep");

                    b.Navigation("MaintenanceTask");

                    b.Navigation("StartExternalDataProcessorStep");

                    b.Navigation("UpdateConfigurationStep");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTaskLogItem", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.InfoBase", "InfoBase")
                        .WithMany()
                        .HasForeignKey("InfoBaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", "Step")
                        .WithMany("Logs")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InfoBase");

                    b.Navigation("Step");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.TechLogSettings", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OneSwiss.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.HasOne("OneSwiss.Server.Models.UsersGroup", "Parent")
                        .WithMany("Groups")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Agent", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Cluster", b =>
                {
                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.ConfigurationRepository", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.Credentials", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("ConfigurationRepositories");

                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.NotificationRecipient", b =>
                {
                    b.Navigation("CustomNotifications");
                });

            modelBuilder.Entity("OneSwiss.Server.Models.UsersGroup", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
