// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnecMonitor.Server;
using OneSwiss.Server;

#nullable disable

namespace OnecMonitor.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.Property<string>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechLogSeancesId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "TechLogSeancesId");

                    b.HasIndex("TechLogSeancesId");

                    b.ToTable("AgentTechLogSeance");
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.Property<string>("InfoBasesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceTasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("InfoBasesId", "MaintenanceTasksId");

                    b.HasIndex("MaintenanceTasksId");

                    b.ToTable("InfoBaseMaintenanceTask");
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.Property<string>("SeancesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplatesId")
                        .HasColumnType("TEXT");

                    b.HasKey("SeancesId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("LogTemplateTechLogSeance");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.CommonSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyMaintenanceTaskCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyMaintenanceTaskInfoBaseCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramBotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommonSettings");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Credentials", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultForClusters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultV8Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Dbms", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dbms");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.ErrorLoggingServiceSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportsTtl")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ErrorLoggingServiceSettings");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.ErrorReport", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Screenshot")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ErrorReports");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.EventLogSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoBaseNameRegex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("EventLogSettings");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.File", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.InfoBase", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.LogTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogTemplates");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLineArguments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeftStepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaintenanceTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeKind")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<string>("PreviousStepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RightStepId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("MaintenanceTaskId");

                    b.ToTable("MaintenanceSteps");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStepLogItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoBaseId");

                    b.HasIndex("StepId");

                    b.ToTable("MaintenanceStepLogs");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("FinishDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFaulted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceTasks");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogFilter", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TechLogFilters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogSeance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirectSending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TechLogSeances");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DbmsId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.HasIndex("DbmsId");

                    b.ToTable("TechLogSettings");
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("TechLogSeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoBaseMaintenanceTask", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.InfoBase", null)
                        .WithMany()
                        .HasForeignKey("InfoBasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceTask", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("SeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.LogTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Agent", "Agent")
                        .WithMany("Clusters")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany("Clusters")
                        .HasForeignKey("CredentialsId");

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.EventLogSettings", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OnecMonitor.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.InfoBase", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Cluster", "Cluster")
                        .WithMany("InfoBases")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany("InfoBases")
                        .HasForeignKey("CredentialsId");

                    b.Navigation("Cluster");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceTask", "MaintenanceTask")
                        .WithMany("Steps")
                        .HasForeignKey("MaintenanceTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("MaintenanceTask");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStepLogItem", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.InfoBase", "InfoBase")
                        .WithMany()
                        .HasForeignKey("InfoBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStep", "Step")
                        .WithMany("Logs")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoBase");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogSettings", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");

                    b.HasOne("OnecMonitor.Server.Models.Dbms", "Dbms")
                        .WithMany()
                        .HasForeignKey("DbmsId");

                    b.Navigation("Credentials");

                    b.Navigation("Dbms");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Agent", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Credentials", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceStep", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.MaintenanceTasks.MaintenanceTask", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
