<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>OneSwiss.OneScript</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OneScript" Version="2.0.0" />
      <PackageReference Include="OneScript.DebugServices" Version="2.0.0" />
      <PackageReference Include="OneScript.Hosting" Version="2.0.0" />
      <PackageReference Include="OneScript.StandardLibrary" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\oneswiss-v8\oneswiss-v8.csproj" />
    </ItemGroup>

</Project>
