namespace OneSwiss.Common.DTO;

public enum MessageType
{
    // System messages
    Error,
    Ok,
    DataStreamHeader,
    DataStreamChunk,

    // Client messages
    AgentInfo,
    InstalledPlatforms,
    RagentServices,
    RasServices,
    CrServerServices,
    Clusters,
    ClusterDetails,
    InfoBases,
    InfoBaseDetails,
    V8Sessions,
    V8Processes,
    SettingsRequest,
    MaintenanceStepNodeLog,
    FileRequest,
    SystemInfoRequest,
    ConfigRepositoryDetailsRequest,
    EdtInstallationsRequest,
    QueueCustomNotificationRequest,
    CrServerPlatformRequest,

    // Server messages
    InstalledPlatformsRequest,
    RagentServicesRequest,
    RasServicesRequest,
    CrServerServicesRequest,
    ClustersRequest,
    ClusterDetailsRequest,
    ChangeClusterParametersRequest,
    ChangeInfoBaseParametersRequest,
    InfoBasesRequest,
    InfoBaseDetailsRequest,
    V8SessionsRequest,
    V8ProcessesRequest,
    Settings,
    MaintenanceTask,
    SystemInfo,
    ConfigRepositoryDetails,
    EdtInstallations,
    CloseV8SessionsRequest,
    V8Platform,
    V8Locks,
    V8LocksRequest,
    V8Servers,
    V8ServersRequest,
    V8Managers,
    V8ManagersRequest,
    V8ManagerServices,
    V8ManagerServicesRequest,
    V8AgentVersion,
    V8AgentVersionRequest,
    V8SecurityProfiles,
    V8SecurityProfilesRequest,
    V8ResourceCounters,
    V8ResourceCountersRequest,
    V8ResourceLimits,
    V8ResourceLimitsRequest,
    V8AssignmentRules,
    V8AssignmentRulesRequest,
    V8ServiceSettings,
    V8ServiceSettingsRequest,
    V8BinaryDataStorages,
    V8BinaryDataStoragesRequest,
    V8Connections,
    V8ConnectionsRequest,
    EventLogReductionResult
}