// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnecMonitor.Server;

#nullable disable

namespace OnecMonitor.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250213212324_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.Property<string>("AgentsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeancesId")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentsId", "SeancesId");

                    b.HasIndex("SeancesId");

                    b.ToTable("AgentTechLogSeance");
                });

            modelBuilder.Entity("InfoBaseUpdateInfoBaseTask", b =>
                {
                    b.Property<string>("InfoBasesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateTasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("InfoBasesId", "UpdateTasksId");

                    b.HasIndex("UpdateTasksId");

                    b.ToTable("InfoBaseUpdateInfoBaseTask");
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.Property<string>("SeancesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplatesId")
                        .HasColumnType("TEXT");

                    b.HasKey("SeancesId", "TemplatesId");

                    b.HasIndex("TemplatesId");

                    b.ToTable("LogTemplateTechLogSeance");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Credentials", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultForClusters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DefaultV8Admin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.InfoBase", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseInternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("CredentialsId");

                    b.ToTable("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.LogTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogTemplates");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogFilter", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TechLogFilters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogSeance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirectSending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StartMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TechLogSeances");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.TechLogSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClickHouseDatabase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClickHouseHost")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClickHousePassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClickHousePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClickHouseUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TechLogSettings");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpdateInfoBaseTasks");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTaskResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoBaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFaulted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateInfoBaseTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfoBaseId");

                    b.HasIndex("UpdateInfoBaseTaskId");

                    b.ToTable("UpdateInfoBaseTaskResults");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTaskResultLogItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateInfoBaseTaskResultId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdateInfoBaseTaskResultId");

                    b.ToTable("UpdateInfoBaseTaskResultLogItem");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.V8Configuration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfiguration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("UpdateInfoBaseTaskV8Configuration", b =>
                {
                    b.Property<string>("ConfigurationsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateTasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigurationsId", "UpdateTasksId");

                    b.HasIndex("UpdateTasksId");

                    b.ToTable("UpdateInfoBaseTaskV8Configuration");
                });

            modelBuilder.Entity("AgentTechLogSeance", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("SeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfoBaseUpdateInfoBaseTask", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.InfoBase", null)
                        .WithMany()
                        .HasForeignKey("InfoBasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.UpdateInfoBaseTask", null)
                        .WithMany()
                        .HasForeignKey("UpdateTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogTemplateTechLogSeance", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.TechLogSeance", null)
                        .WithMany()
                        .HasForeignKey("SeancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.LogTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Agent", "Agent")
                        .WithMany("Clusters")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany("Clusters")
                        .HasForeignKey("CredentialsId");

                    b.Navigation("Agent");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.InfoBase", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.Cluster", "Cluster")
                        .WithMany("InfoBases")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.Credentials", "Credentials")
                        .WithMany("InfoBases")
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTaskResult", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.InfoBase", "InfoBase")
                        .WithMany()
                        .HasForeignKey("InfoBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.UpdateInfoBaseTask", "UpdateInfoBaseTask")
                        .WithMany("Results")
                        .HasForeignKey("UpdateInfoBaseTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfoBase");

                    b.Navigation("UpdateInfoBaseTask");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTaskResultLogItem", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.UpdateInfoBaseTaskResult", "UpdateInfoBaseTaskResult")
                        .WithMany("Log")
                        .HasForeignKey("UpdateInfoBaseTaskResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdateInfoBaseTaskResult");
                });

            modelBuilder.Entity("UpdateInfoBaseTaskV8Configuration", b =>
                {
                    b.HasOne("OnecMonitor.Server.Models.V8Configuration", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnecMonitor.Server.Models.UpdateInfoBaseTask", null)
                        .WithMany()
                        .HasForeignKey("UpdateTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Agent", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Cluster", b =>
                {
                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.Credentials", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("InfoBases");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTask", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("OnecMonitor.Server.Models.UpdateInfoBaseTaskResult", b =>
                {
                    b.Navigation("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
